# Generated by Django 4.2.3 on 2023-08-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='value',
            field=models.CharField(choices=[('during', 'during'), ('finished', 'finished')], default='during', max_length=10),
        ),
    ]
